build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - "ProjectStatisticsReport"
    - "ComplexityReport"
    - "NotificationReport"

output-reports:
  active: true
  exclude: []

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  NewLineAtEndOfFile:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"

complexity:
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8

exceptions:
  TooGenericExceptionCaught:
    active: false

moneytracker-conventions:
  active: true
  DataClassMultilineProperties:
    active: true
  MapperFunctionPrefix:
    active: true
  TopLevelDeclarationOrder:
    active: true
